apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: block-log4shell
spec:
  gateways:
  - todolist
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: todolist.default.svc.cluster.local
        port:
          number: 80
